export const watermarkPatterns = [
  /as an ai language model/i,
  /generated by ai/i,
  /ai-generated content/i,
  /this content was created by ai/i,
  /produced by artificial intelligence/i,
  /as an artificial intelligence/i,
  /as a large language model/i,
  /my purpose is to assist/i,
  /i don't have personal experiences/i,
  /i don't have feelings or consciousness/i,
  /as an ai assistant/i,
  /as an ai, i don't have/i,
  /i'm an ai trained by/i,
  /my training data includes/i,
  /i was created by/i,
  /developed by openai/i
];